helmDefaults:
  wait: true
  atomic: true
  timeout: 300

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    createNamespace: true
    values:
      - k8s/base/kube-prometheus-stack/values-helm.yaml
