helmDefaults:
  wait: true
  atomic: true
  timeout: 300

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    createNamespace: true
    values:
      - kube-prometheus-stack/values-helm.yaml

  - name: pihole
    namespace: pihole
    chart: mojo2600/pihole
    createNamespace: true
    values:
      - pihole/values-helm.yaml
